### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by kohjp** [kohjp/pre-project-fe-tutorial#1]
### 만들고자 하는 서비스
Todo 리스트

### 필수 기능
1. [ ] Create : Todo 생성
2. [ ] Read : Todo 조회
3. [ ] Update : Todo 수정
4. [ ] Delete : Todo 삭제

### 예상 작업 시간
6h
